version: 2
jobs:
  build-server-run-api-tests:
    working_directory: ~/app
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm root packages
          command: npm install
          paths:
            - node_modules
      - run:
          name: Install server
          command: cd server && npm install
      - run:
          name: Run API Tests
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-server-run-api-tests:
          filters:
            branches:
              only: master